# Generated by Django 3.1 on 2020-10-27 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import website.managers
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', website.models.CustomEmailField(max_length=64, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=64, verbose_name='nama depan')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='nama belakang')),
                ('hp', models.CharField(max_length=14, verbose_name='hp')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', website.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kantorpos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=8, null=True)),
                ('regional', models.CharField(max_length=2, null=True)),
                ('nama', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'kantor pos',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumlah_item', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_metode', models.CharField(max_length=32)),
                ('deskripsi', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'metode pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Properti',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('deskripsi', models.TextField()),
                ('alamat', models.CharField(max_length=128)),
                ('luas_tanah', models.IntegerField()),
                ('luas_bangunan', models.IntegerField()),
                ('lantai', models.IntegerField()),
                ('listrik', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('ketersediaan', models.IntegerField(choices=[(0, 'Tidak ada'), (1, 'Ada')], default=1)),
                ('foto', models.ImageField(help_text='Maximum file size allowed is 3Mb', upload_to=website.models.PathAndRename('images/properti'), validators=[website.models.validate_image], verbose_name='Foto properti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kantropos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kantorpos')),
            ],
            options={
                'verbose_name_plural': 'Properti',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=64)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField(null=True)),
                ('stok', models.IntegerField()),
                ('foto', models.ImageField(help_text='Maximum file size allowed is 3Mb', upload_to=website.models.PathAndRename('images/produk'), validators=[website.models.validate_image], verbose_name='Foto produk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kategori')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.CreateModel(
            name='permintaan_sewa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('telepon', models.CharField(max_length=64)),
                ('instansi', models.CharField(max_length=64, null=True)),
                ('catatan', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('properti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.properti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=16, unique=True)),
                ('nama_penerima', models.CharField(max_length=64)),
                ('telepon_penerima', models.CharField(max_length=64)),
                ('alamat_pengiriman', models.CharField(max_length=64)),
                ('subtotal', models.IntegerField()),
                ('ongkos_kirim', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
                ('status_pembayaran', models.IntegerField(choices=[(0, 'Belum dibayar'), (1, 'Sudah dibayar, belum diverfikasi'), (2, 'Sudah diverifikasi')], default=0)),
                ('jumlah_item', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bukti_pembayaran', models.ImageField(help_text='Maximum file size allowed is 3Mb', null=True, upload_to=website.models.PathAndRename('images/bukti_pembayaran'), validators=[website.models.validate_image])),
                ('uploaded_at', models.DateTimeField(null=True)),
                ('kantorpos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kantorpos')),
                ('metode_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.metodepembayaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'order',
            },
        ),
        migrations.CreateModel(
            name='IsiKeranjang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keranjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.keranjang')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.produk')),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.order')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.produk')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='keranjang',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.keranjang'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
