# Generated by Django 3.1 on 2020-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properti',
            old_name='luas',
            new_name='luas_bangunan',
        ),
        migrations.AddField(
            model_name='properti',
            name='alamat',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properti',
            name='luas_tanah',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='nama belakang'),
        ),
    ]
