# Generated by Django 3.1 on 2020-09-21 13:24

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200916_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=website.models.CustomEmailField(max_length=64, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='nama depan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='nama belakang'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='password'),
        ),
    ]
