# Generated by Django 3.1 on 2020-10-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_properti_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(max_length=64),
        ),
    ]
