# Generated by Django 3.1 on 2020-10-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201025_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properti',
            name='lebar',
        ),
        migrations.RemoveField(
            model_name='properti',
            name='panjang',
        ),
        migrations.AlterField(
            model_name='order',
            name='status_pembayaran',
            field=models.IntegerField(choices=[(0, 'Belum dibayar'), (1, 'Sudah dibayar, belum diverfikasi'), (2, 'Sudah diverifikasi')], default=0),
        ),
        migrations.AlterField(
            model_name='properti',
            name='ketersediaan',
            field=models.IntegerField(choices=[(0, 'Tidak ada'), (1, 'Ada')], default=1),
        ),
    ]
