# Generated by Django 3.1 on 2020-10-26 04:09

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201025_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailorder',
            old_name='transaksi',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='bukti_pembayaran',
            field=models.ImageField(null=True, upload_to='', verbose_name=website.models.PathAndRename('images/bukti_pembayaran')),
        ),
    ]
