# Generated by Django 3.1 on 2020-10-27 04:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201027_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 27, 4, 13, 55, 137559, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
