# Generated by Django 3.1 on 2020-09-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200921_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keranjang',
            name='user',
        ),
        migrations.AlterField(
            model_name='keranjang',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
