# Generated by Django 3.1 on 2020-10-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201026_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='properti',
            name='kode',
            field=models.CharField(default='9BB53001D83E', max_length=16, unique=True),
        ),
    ]
