# Generated by Django 3.1 on 2020-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_properti_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properti',
            name='kode',
            field=models.CharField(default='F32C693B6506', max_length=16, unique=True),
        ),
    ]
