# Generated by Django 3.1 on 2020-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20201026_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kode',
            field=models.CharField(default='6EE97C4A8B07', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='properti',
            name='kode',
            field=models.CharField(default='CD51B2D22FB6', max_length=16, unique=True),
        ),
    ]
