# Generated by Django 3.1 on 2020-10-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201026_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kode',
            field=models.CharField(default='7115E7D3568C', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='properti',
            name='kode',
            field=models.CharField(default='3D16A83E1475', max_length=16, unique=True),
        ),
    ]
