# Generated by Django 3.1 on 2020-09-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200923_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keranjang',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.keranjang'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.transaksi'),
        ),
        migrations.AlterField(
            model_name='isikeranjang',
            name='keranjang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.keranjang'),
        ),
    ]
